work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN

# weights1: ./work_dir/recognition/ntu-xsub/ST_GCN/epoch9_model1.pt
# weights2: ./work_dir/recognition/ntu-xsub/ST_GCN/epoch9_model2.pt

feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../p3d_gcn_pytorch/data/NTU-RGB-D/xsub/train_data.npy
  label_path: ../p3d_gcn_pytorch/data/NTU-RGB-D/xsub/train_label.pkl
test_feeder_args:
  data_path: ../p3d_gcn_pytorch/data/NTU-RGB-D/xsub/val_data.npy
  label_path: ../p3d_gcn_pytorch/data/NTU-RGB-D/xsub/val_label.pkl

model1: net.st_gcn.Model
model1_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    max_hop: 3

model2: net.utils.adj_learn.AdjacencyLearn
model2_args:
  n_in_enc: 150
  n_hid_enc: 128
  edge_types: 4
  n_in_dec: 3
  n_hid_dec: 128
  node_num: 25

weight_decay: 0.0001
base_lr1: 0.1
base_lr2: 0.0005
step: [40, 70, 90]

device: [1,7]
batch_size: 16
test_batch_size: 16
start_epoch: 0
num_epoch: 112