work_dir: ./work_dir/recognition/ntu-xsub/AS_GCN

feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/xsub/train_label.pkl
  random_move: False
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/val_data.npy
  label_path: ./data/NTU-RGB-D/xsub/val_label.pkl


model: net.as_gcn.Model
model_args:
  n_in_enc: 150
  n_hid_enc: 128
  edge_type_act: 4
  n_in_dec: 3
  n_hid_dec: 128
  
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    max_hop: 4

# weights: ./work_dir/recognition/ntu-xsub/AS_GCN/epoch2_model.pt

w_pred: 1.
weight_decay: 0.0001
base_lr_rec: 0.1
base_lr_aim: 0.0001
step: [25, 45, 65]
start_epoch: 0
device: [5,6]
batch_size: 16
test_batch_size: 16
num_epoch: 80
